name: bonus_app
description: Bonus App

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.0.1
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.10.3
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/qrcode.svg
  - assets/hotcashbacks/File1.jpeg
  - assets/hotcashbacks/File2.png
  - assets/hotcashbacks/File3.jpeg
  - assets/hotcashbacks/File4.jpeg
  - assets/hotcashbacks/File5.jpeg
  - assets/hotcashbacks/File6.png
  - assets/novelty/File1.jpg
  - assets/novelty/File2.jpg
  - assets/novelty/File3.jpeg
  - assets/novelty/File4.jpg
  - assets/novelty/File5.jpg
  - assets/novelty/File6.jpg
  - assets/novelty/File7.jpg
  - assets/novelty/File7.jpg
  - assets/novelty/File9.jpg
  - assets/logos/autoservice.png
  - assets/logos/barber.png
  - assets/logos/cinemawolrd.png
  - assets/logos/englishcenter.png
  - assets/logos/Hinkali.png
  - assets/logos/italiano_pizza.jpg
  - assets/logos/sportmaster.png
  - assets/logos/ukrfood.png